- Media:
  - Plex:
      icon: plex.png
      href: http://sanjck.com:42069
#      description: Plex Server
  - Jellyfin:
      icon: jellyfin.png
#      href: http://74.64.242.199:58035
      href: jellyfin
