---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /srv/docker/plex/config:/config
      - /mnt/zvalbard/plex/tv:/tv
      - /mnt/zvalbard/plex/movies:/movies
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 32400:32400
    restart: unless-stopped
