services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /srv/docker/homepage/config:/app/config # Make sure your local config directory exists
    environment:
      PUID: $PUID
      PGID: $PGID
